services:

  jenkins:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/jenkins/jenkins:lts
    environment:
      CONF_ALLOW_RUNS_ON_MASTER: 'true'
    build:
      context: .
    user: jenkins
    container_name: jenkins
    ports:
    - target: 8080
      published: 8888
    - target: 50000
      published: 50000
    volumes:
    - type: bind
      source: '/var/run/docker.sock'
      target: '/var/run/docker.sock'
      read_only: true
    - type: bind
      source: '/opt/jenkins_jobs'
      target: '/var/jenkins_home/jobs'
      read_only: false
    - type: bind
      source: './env/${JENKINS_ENV_FILE}'
      target: '/var/jenkins_home/jenkins.yaml'
      read_only: false
#    - type: bind
#      source: '${PWD}/key/master.key' # Move the key from repo to a restricted folder and specify the path here 
#      target: '/var/jenkins_home/secrets/master.key'
#      read_only: false
    networks:
    - heuristic-network
    tty: true

networks:
  heuristic-network:
    driver: bridge